INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('added', '', '', 0, 0);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Cbom', 'كوب', 'قنبلة', 15, 10);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Clut', 'كوب', 'لوتس', 17, 12);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Cman', 'كوب', 'مانجة', 15, 10);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Cmed', 'كوب', 'مدلعة', 15, 10);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Cnut', 'كوب', 'نوتيلا', 15, 10);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('cofee', 'قهوة', 'وسط', 10, 6);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Dislut', 'دسباسيتو', 'لوتس', 0, 30);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Disnut', 'دسباسيتو', 'نوتيلا', 0, 25);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Fben', 'فورم', 'بين نارين', 110, 90);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Fcrm', 'فورم', 'كريمة', 90, 70);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Flut', 'فورم', 'لوتس', 145, 120);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Fman', 'فورم', 'مانجة', 110, 85);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Fmed', 'فورم', 'مدلعة', 110, 85);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Fnap', 'فورم', 'نابلسية', 105, 80);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Fnut', 'فورم', 'نوتيلا', 100, 80);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Frise', 'ارز', 'فرن', 0, 6);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Kben', 'كلاسيك', 'بين نارين', 100, 16);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Kcon', 'كلاسيك', 'كونو', 120, 15);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Kcrm', 'كلاسيك', 'كريمة', 80, 10);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Kgcrm', 'كلاسيك', 'جلاش كريمة', 85, 12);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Klut', 'كلاسيك', 'لوتس', 135, 18);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Kman', 'كلاسيك', 'مانجة', 100, 15);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Kmed', 'كلاسيك', 'مدلعة', 100, 15);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Kmix', 'كلاسيك', 'مشكل', 110, 15);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Kmks', 'كلاسيك', 'مكسرات', 130, 16);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Knap', 'كلاسيك', 'نابلسية', 95, 15);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Knut', 'كلاسيك', 'نوتيلا', 90, 12.5);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Ksad', 'كلاسيك', 'سادة', 70, 10);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Mfor', 'ميكسات', 'فور سيزون', 165, 145);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Mlutman', 'ميكسات', 'لوتس+مانجة', 130, 100);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Mmanmed', 'ميكسات', 'مدلعة+مانجة', 115, 90);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Mmedfrt', 'ميكسات', 'مدلعة فواكة', 160, 140);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Mnutman', 'ميكسات', 'نوتيلا+مانجة', 115, 90);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('MTlutman', 'ميكسات', 'تورتةلوتس مانجة', 180, 170);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('Orise', 'ارز', 'عادي', 0, 5);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('pepsi', 'بيبسي', 'كان', 0, 6);
INSERT INTO kunafahut.types (id, type, name, big, medium) VALUES ('water', 'مياة', 'معدنية', 0, 4);